### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by WennderSantos** [hapijs/code#114]
Hey

When I try to run my tests using versions 5.0.0 or 5.0.1 I get this error:

/Users/wennderangelodossantos/project/node-tdd/node_modules/code/lib/index.js:402
internals.reject = async function (/* type, message */) {
                         ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/wennderangelodossantos/project/node-tdd/test/main.js:8:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at testFiles.forEach (/Users/wennderangelodossantos/project/node-tdd/node_modules/lab/lib/cli.js:121:21)
    at Array.forEach (native)
    at Object.internals.traverse (/Users/wennderangelodossantos/project/node-tdd/node_modules/lab/lib/cli.js:117:15)
    at Object.exports.run (/Users/wennderangelodossantos/project/node-tdd/node_modules/lab/lib/cli.js:62:31)
    at Object.<anonymous> (/Users/wennderangelodossantos/project/node-tdd/node_modules/lab/bin/lab:50:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3

My package.json
`{
  "name": "node-tdd",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "lab -r console --verbose"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "co": "^4.6.0",
    "code": "4.1.0",
    "lab": "^14.3.1",
    "standard": "^10.0.3"
  },
  "dependencies": {
    "hapi": "^16.6.2"
  }
}`

This is just a study project.

I tried with versions before 5.0.0 and everything is fine.

**Comment by cjihrig** [comment]
You have to be using Node 8, as code 5+ uses `async` functions.

**Comment by WennderSantos** [comment]
Now it works, thanks, @cjihrig!
